### ISSUE TITLE
Week 1 Individual Project Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [woestmab/IndieSpringProject#1]
Hi Brian,

You are off to a good start with  solid problem statement in a space you really understand. Great choice!  

Next up:

- [ ] Add a time log to capture hours spent on your individual project and class exercises/readings/activities
- [ ] Flush out more detail in your project plan, think about the smaller tasks that you will need to complete. You might take a look at the Fat Bike Trail Reports repository for an example of the level detail I'd like you to get to.
- [ ] You have a lot of opportunity to use some of the data that exists around public transport and mapping. For example: https://developers.google.com/transit/?hl=en  Looking forward to following your research on the options.
- [ ] Screen design - this will likely help quite a bit with planning.

**Comment by woestmab** [comment]
Added details to the project plan and a time log.  I'm currently working on some stuff so I will add more to the log and journal before tomorrow.
