### ISSUE TITLE
Savannah's Review

### ISSUE THREAD

**Issue by savannaholson** [woestmab/IndieSpringProject#2]
# Design/Code Review 1

#### Reviewer: Savannah

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Problem Statement**|Does it exist?| reviewer rating/comments go here|
||Does the problem statement accurately describe project purpose?| Yes |
||Is the problem statement professional? Think of prospective employers viewing this as part of the developer's portfolio.| Yes |
||What is good?| It is somewhat open to allow for some changes |
||What could be improved?| No Idea |
|**Project Plan**|Does it exist?| Y |
||Does it demonstrate the developer has thought about all the tasks needed to complete the project?| Yes | 
||Does it provide enough detail to guide the developer through their development?| Yes | 
||What is good?| It estabishes goals without going too far into details | 
||What could be improved?| No Idea. |
|**UI design**|Does it exist?| Yes |
||Is the navigation/flow through the application logical and easy to use?| Yes |
||Is the order in which the fields are displayed and form fields entered logical and easy to use?| Yes |
||What data missing?| I dont know |
||Is there data that is not used?| Not sure |
||What is good?| It seems to be very straitforward |
||What could be improved?| Not sure |
|**Data model**|Does it exist?| Yes |
||Is everything on the screens represented in the model?| I think so? |
||Does the model represent good database design? | Looks like it |
||What is good?| In third normal form |
||What could be better?| Naming could be improved |
|**Additional design documents**| | ? |
|**Application structure in IntelliJ**|Does it exist?| Yes |
||src directory with well-named packages for entity, controller, persistence| no? |
||tests directory| Yes |
||web directory| yes |
||Other comments/notes?|  |
|**JSPs**|Do they exist?| yes |
||Is templating used (for example, header.jsp, footer.jsp, etc.)?| no |
||Is there business logic mixed in the JSPs?| no |
||CSS?| Yes |
||Other comments/notes?| nice calender already exists. |
|**Entities/DAOs/Controllers**|Do they exist?| no |
|**Java code quality**|Are methods single-purpose?| Perfect due to lack of code |
||Are classes appropriately-sized classes (no monster classes)?| |
||Are the same lines of code repeated at all?| | 
||Do any classes perform very similar functions that could be candidates for super/subclass relationships?| |
||Are any values hard-coded that should be in a properties file?| |
||Are variable names descriptive?| |
||Are there many branches or loops that could be simplified or broken up into smaller methods?| |
||Do the DAOs use Hibernate? No hard-coded sql!| |
||Other comments/notes?| perfect due to lack of code |
|**Logging**|Has log4J been added?| yes |
||Are there logging statements in the code?| no |
||Are appropriate logging levels used? Info, debug, error, for example.| |
||Are there any System.out.printlns in the code?| |
||Other comments/notes?| no code. |
|**Unit Tests**|Do they exist?| not existing yet |
||Do the tests pass?| |
||What is the current code coverage?| |
||Is each test truly a unit test or are they functional tests?| |
||Other comments/notes?| |
|**Web Service/API integration**|Has a web service/api been selected? | Maybe? |
||What web services/apis might work well with this application?| |
|**Independent research topic**| Has a topic been selected?| Spring?  |
||What topic/s might fit well in this application?| |

**Comment by woestmab** [comment]
Made some changes to the database as suggested.
